name: Build and Push Docker Image

on:
  push:
    branches:
    - main
  release:
    types: [published]


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract release version
        id: extract_version
        run: echo "::set-output name=VERSION::$(echo ${{ github.ref_name }} | sed 's/v//')"

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.extract_version.outputs.VERSION }}
          build-args: |
            VERSION=${{ steps.extract_version.outputs.VERSION }}